server:
  # port which the app is served
  port: 8000
  # the route which you access the file server
  route: /
  # path to the folder you are serving
  path: /usr/share/httpfileserver
logging:
  # prefix for each log
  prefix: Server
  # log levels
  # error, warn, info, debug, trace
  level: debug
  # log output
  # /dev/stderr : standard error
  out: /dev/stderr
  # print the function and file that the called the log
  print_caller: true
  # format of the time in log
  time_format: "2006-01-02 15:04:05"

