zaplogger:
  level: debug
  encoding: json
  outputPaths: ["stdout"]
  errorOutputPaths: ["stderr"]
  development: true
  disableCaller: false
  disableStackTrace: false
  encoderConfig:
    messageKey: message
    levelKey: level
    levelEncoder: lowercase

http:
  headers:
    RSS: [RSS]
    RSS2: [RSS2]
  # interval which to send data to the server
  # s for second
  # m for minute
  # h for hour
  interval: 3s
  # destination host
  destination: http://localhost:8000
  # timeout for sending to destination
  # s for second
  # m for minute
  # h for hour
  timeout: 10s
  # s for second
  # m for minute
  # h for hour
  retry_interval: 50s

db:
  persist: true
  persist_interval: 3s
  eviction: true
  eviction_interval: 3s
  db_path: /tmp/db.txt
  retry_db_path: /tmp/retdb.txt
