zaplogger:
  level: debug
  encoding: json
  outputPaths: ["stdout"]
  errorOutputPaths: ["stderr"]
  development: true
  disableCaller: false
  disableStackTrace: false
  encoderConfig:
    messageKey: message
    levelKey: level
    levelEncoder: lowercase

http:
  # interval which to send data to the server
  # s for second
  # m for minute
  # h for hour
  # d for day
  # w for week
  interval: 50s
  # destination host
  destination: localhost:8000
  # s for second
  # m for minute
  retry_interval: 50s
