name: ci
on:
  push:
    tags:
      - "v*"
    paths:
      - "logging/*"
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - 
       name: 'Login to GitHub Container Registry'
       uses: docker/login-action@v1
       with:
         registry: ghcr.io
         username: ${{github.actor}}
         password: ${{secrets.GITHUB_TOKEN}}

      -
        name: Build
        uses: docker/build-push-action@v5
        with:
          context: .
          push: false
          tags: ghcr.io/alipourhabibi/exercise-journals/logging:{{ github.ref }}
      - 
       name: 'Build And Push Image'
       run: |
         docker push ghcr.io/alipourhabibi/exercise-journals/logging:{{ github.ref }}
