name: Echo ci

on:
  push:
    tags:
      - "v*"
    paths:
      - "echo/*"

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - 
       name: 'Login to GitHub Container Registry'
       uses: docker/login-action@v1
       with:
         registry: ghcr.io
         username: ${{github.actor}}
         password: ${{secrets.GITHUB_TOKEN}}

      -
        name: Build
        uses: docker/build-push-action@v5
        with:
          context: echo/.
          push: true
          tags: ghcr.io/alipourhabibi/exercise-journals-echo:latest

      - name: Install Hurl
        run: |
          VERSION=4.3.0
          curl --silent --location https://github.com/Orange-OpenSource/hurl/releases/download/$VERSION/hurl-$VERSION-x86_64-unknown-linux-gnu.tar.gz | tar xvz -C /tmp
          cp /tmp/hurl-4.3.0-x86_64-unknown-linux-gnu/bin/hurl /bin/hurl
      -
        name: Run docker image
        run: docker run -d --rm --name http-echo --network=host ghcr.io/alipourhabibi/exercise-journals-echo:latest

      - name: Run Hurl tests
        run: |
          for file in $(find ./echo/hurl-tests -name "*.hurl"); do
            hurl --test "$file" --variable host=localhost:8082
          done
